create or replace function public.get_engine_config() returns jsonb language sql security definer set search_path='' as $$
select jsonb_build_object('ledger_asset',public.engine_ledger_asset(),'real_enabled',public.module_enabled('real_accounts'),'server_time',now(),'indices',coalesce((select jsonb_agg(jsonb_build_object('code',code,'display_name',display_name,'interval_ms',tick_interval_ms,'decimals',decimals,'status',status) order by sort_order) from public.engine_indices where execution_mode='DEMO'),'[]'::jsonb),'enabled_contract_types',(select enabled_contract_types from public.engine_policy_versions order by version desc limit 1)) $$;

create or replace function public.get_recent_ticks(p_index text,p_limit integer default 100) returns table(index_code text,tick_no bigint,scheduled_at timestamptz,price numeric,digit smallint) language sql security definer set search_path='' as $$
select t.index_code,t.tick_no,t.scheduled_at,t.price,t.digit from public.index_ticks t where t.index_code=p_index and t.execution_mode='DEMO' order by t.tick_no desc limit least(greatest(coalesce(p_limit,100),1),500) $$;
create or replace function public.get_ticks_since(p_index text,p_after_tick_no bigint,p_limit integer default 100) returns table(index_code text,tick_no bigint,scheduled_at timestamptz,price numeric,digit smallint) language sql security definer set search_path='' as $$
select t.index_code,t.tick_no,t.scheduled_at,t.price,t.digit from public.index_ticks t where t.index_code=p_index and t.execution_mode='DEMO' and t.tick_no>coalesce(p_after_tick_no,0) order by t.tick_no limit least(greatest(coalesce(p_limit,100),1),500) $$;
create or replace function public.list_my_contracts(p_account_id uuid,p_state text default null,p_before timestamptz default null,p_limit integer default 50) returns setof public.engine_contracts language sql security definer set search_path='' as $$
select c.* from public.engine_contracts c join public.trading_accounts a on a.id=c.trading_account_id where c.trading_account_id=p_account_id and a.user_id=auth.uid() and (p_state is null or c.state=p_state) and (p_before is null or c.created_at<p_before) order by c.created_at desc limit least(greatest(coalesce(p_limit,50),1),100) $$;
create or replace function public.get_epoch_proofs(p_account_id uuid,p_index text,p_limit integer default 30) returns table(id uuid,starts_at timestamptz,ends_at timestamptz,seed_commitment text,prev_chain_hash text,chain_hash text,revealed_seed text,revealed_at timestamptz) language sql security definer set search_path='' as $$
select e.id,e.starts_at,e.ends_at,e.seed_commitment,e.prev_chain_hash,e.chain_hash,e.revealed_seed,e.revealed_at from public.engine_epochs e join public.trading_accounts a on a.id=p_account_id where a.user_id=auth.uid() and e.execution_mode=a.execution_mode order by e.starts_at desc limit least(greatest(coalesce(p_limit,30),1),500) $$;

revoke all on function public.get_engine_config(),public.get_recent_ticks(text,integer),public.get_ticks_since(text,bigint,integer),public.list_my_contracts(uuid,text,timestamptz,integer),public.get_epoch_proofs(uuid,text,integer) from public,anon;
grant execute on function public.get_engine_config(),public.get_recent_ticks(text,integer),public.get_ticks_since(text,bigint,integer),public.list_my_contracts(uuid,text,timestamptz,integer),public.get_epoch_proofs(uuid,text,integer) to authenticated;
